---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Loading data

NYC Airbnb data:

```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  select(borough = neighbourhood_group, 
         neighbourhood, stars, price, room_type, lat, long) |> 
  drop_na(stars) |> 
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```

# Making plots

##scatter

```{r}
nyc_airbnb |> 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", stars)) |> 
  plot_ly(x = ~lat, y = ~long, color = ~price, text = ~text_label,
          type = "scatter", mode = "markers", alpha = .5)
```

## Boxplot

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price))|> 
  plot_ly(y = ~price, x=~neighbourhood, color = ~neighbourhood,
          type = "box", colors = "viridis")
```

## barplot

```{r}
nyc_airbnb |> 
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly( x=~neighbourhood, y=~n, color = ~neighbourhood,
           type = "bar", colors = "viridis")
```

#ggplotly

```{r}
scatter_ggplot = 
  nyc_airbnb |>
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```

